import sys

sys.path.append('..')

import csv_helper as csv


if __name__ == '__main__':

    tables = {'wqip_quarterly_performance_2023_r1': 'py1-2023-wqip-quarterly-performance-report-1.csv',
              'wqip_quarterly_performance_2023_r2': 'py1-2023-wqip-quarterly-performance-report-2.csv',
              'wqip_quarterly_performance_2023_r3': 'py1-2023-wqip-quarterly-performance-report-3.csv',
              'wqip_quarterly_performance_2024_r1': 'py2-2024-wqip-quarterly-performance-report-1.csv'}

    types = {}
    # {'table': {'col': 'type'}}

    replaces = {}
    # {'bad_name1': 'good_name1', 'bad_name2': 'good_name2'}

    csv.create_tables(tables, types, replaces)
    csv.read_data(tables, types, replaces)

    sql = "drop table if exists wqip_quarterly_performance"
    csv.db_exec_sql(sql)

    print("creating table wqip_quarterly_performance...")

    sql = """create table wqip_quarterly_performance (
                 achievement_points_antipsych varchar(1),
                 achievement_points_fall varchar(1),
                 achievement_points_pu varchar(1),
                 acuity_area_score varchar(11),
                 acuity_points_earned varchar(11),
                 acuity_possible_points varchar(2),
                 antipsych_denom_annotation varchar(1),
                 antipsych_denom_pyr_annotation varchar(1),
                 antipsych_denom_pyr varchar(3),
                 antipsych_denom varchar(3),
                 antipsych_metric_score varchar(1),
                 antipsych_num_annotation varchar(1),
                 antipsych_num_pyr_annotation varchar(1),
                 antipsych_num_pyr varchar(3),
                 antipsych_num varchar(3),
                 antipsych_rate_annotation varchar(1),
                 antipsych_rate_pyr_annotation varchar(1),
                 antipsych_rate_pyr varchar(7),
                 antipsych_rate varchar(11),
                 ccn varchar(6),
                 cna_days_compliant varchar(11),
                 cna_rate varchar(5),
                 facilityid varchar(9),
                 facility_name varchar(61),
                 fall_denom_annotation varchar(1),
                 fall_denom_pyr_annotation varchar(1),
                 fall_denom_pyr varchar(4),
                 fall_denom varchar(4),
                 fall_metric_score varchar(1),
                 fall_num_annotation varchar(1),
                 fall_num_pyr_annotation varchar(1),
                 fall_num_pyr varchar(2),
                 fall_num varchar(2),
                 fall_rate_annotation varchar(1),
                 fall_rate_pyr_annotation varchar(1),
                 fall_rate_pyr varchar(7),
                 fall_rate varchar(11),
                 gap_closure_antipsych_annotation varchar(1),
                 gap_closure_antipsych varchar(11),
                 gap_closure_fall_annotation varchar(1),
                 gap_closure_fall varchar(11),
                 gap_closure_pu_annotation varchar(1),
                 gap_closure_pu varchar(11),
                 hcai_id varchar(9),
                 improvement_points_antipsych varchar(1),
                 improvement_points_fall varchar(1),
                 improvement_points_pu varchar(1),
                 ltmw_denom_annotation varchar(1),
                 ltmw_denom varchar(3),
                 ltmw_num_annotation varchar(1),
                 ltmw_num varchar(2),
                 ltmw_rate_annotation varchar(1),
                 ltmw_rate varchar(11),
                 lvn_days_compliant varchar(10),
                 lvn_rate varchar(5),
                 mds_area_score varchar(11),
                 mds_data_completeness varchar(11),
                 mds_points_earned varchar(2),
                 mds_points_possible varchar(2),
                 medi_cal_share_area_score varchar(3),
                 medi_cal_share_footnote varchar(140),
                 medi_cal_share_points_earned varchar(1),
                 medi_cal_share_possible_points varchar(1),
                 medi_cal_share_rate varchar(11),
                 npi1 varchar(10),
                 npi2 varchar(10),
                 npi3 varchar(10),
                 npi varchar(22),
                 pu_denom_annotation varchar(1),
                 pu_denom_pyr_annotation varchar(1),
                 pu_denom_pyr varchar(3),
                 pu_denom varchar(3),
                 pu_metric_score varchar(1),
                 pu_num_annotation varchar(1),
                 pu_num_pyr_annotation varchar(1),
                 pu_num_pyr varchar(3),
                 pu_num varchar(3),
                 pu_rate_annotation varchar(1),
                 pu_rate_pyr_annotation varchar(1),
                 pu_rate_pyr varchar(7),
                 pu_rate varchar(7),
                 raw_mds_score varchar(11),
                 raw_score_cna varchar(1),
                 raw_score_lvn varchar(1),
                 raw_score_rn varchar(1),
                 raw_score_total_nursing varchar(1),
                 raw_score_weekend varchar(1),
                 re_completeness_area_score varchar(3),
                 re_completeness_points_earned varchar(2),
                 re_completeness_points_possible varchar(2),
                 re_completeness_rate varchar(11),
                 rn_days_compliant varchar(10),
                 rn_rate varchar(5),
                 score_cna varchar(11),
                 score_lvn varchar(11),
                 score_rn varchar(11),
                 score_total_nursing varchar(11),
                 score_total_weekend_nursing varchar(11),
                 staffing_turnover_rate varchar(5),
                 total_nursing_days_compliant varchar(11),
                 total_nursing_rate varchar(6),
                 total_weekend_days_compliant varchar(11),
                 total_weekend_nursing_rate varchar(6),
                 turnover_area_score varchar(11),
                 turnover_points_earned varchar(1),
                 turnover_possible_points varchar(1),
                 quarter char(7))"""

    csv.db_exec_sql(sql) 

    sql = """insert into wqip_quarterly_performance (
                 achievement_points_antipsych,
                 achievement_points_fall,
                 achievement_points_pu,
                 acuity_area_score,
                 acuity_points_earned,
                 acuity_possible_points,
                 antipsych_denom_annotation,
                 antipsych_denom_pyr_annotation,
                 antipsych_denom_pyr,
                 antipsych_denom,
                 antipsych_metric_score,
                 antipsych_num_annotation,
                 antipsych_num_pyr_annotation,
                 antipsych_num_pyr,
                 antipsych_num,
                 antipsych_rate_annotation,
                 antipsych_rate_pyr_annotation,
                 antipsych_rate_pyr,
                 antipsych_rate,
                 ccn,
                 cna_days_compliant,
                 cna_rate,
                 facilityid,
                 facility_name,
                 fall_denom_annotation,
                 fall_denom_pyr_annotation,
                 fall_denom_pyr,
                 fall_denom,
                 fall_metric_score,
                 fall_num_annotation,
                 fall_num_pyr_annotation,
                 fall_num_pyr,
                 fall_num,
                 fall_rate_annotation,
                 fall_rate_pyr_annotation,
                 fall_rate_pyr,
                 fall_rate,
                 gap_closure_antipsych_annotation,
                 gap_closure_antipsych,
                 gap_closure_fall_annotation,
                 gap_closure_fall,
                 gap_closure_pu_annotation,
                 gap_closure_pu,
                 hcai_id,
                 improvement_points_antipsych,
                 improvement_points_fall,
                 improvement_points_pu,
                 lvn_days_compliant,
                 lvn_rate,
                 mds_area_score,
                 mds_data_completeness,
                 mds_points_earned,
                 mds_points_possible,
                 medi_cal_share_area_score,
                 medi_cal_share_footnote,
                 medi_cal_share_points_earned,
                 medi_cal_share_possible_points,
                 medi_cal_share_rate,
                 npi,
                 pu_denom_annotation,
                 pu_denom_pyr_annotation,
                 pu_denom_pyr,
                 pu_denom,
                 pu_metric_score,
                 pu_num_annotation,
                 pu_num_pyr_annotation,
                 pu_num_pyr,
                 pu_num,
                 pu_rate_annotation,
                 pu_rate_pyr_annotation,
                 pu_rate_pyr,
                 pu_rate,
                 raw_mds_score,
                 raw_score_cna,
                 raw_score_lvn,
                 raw_score_rn,
                 raw_score_total_nursing,
                 raw_score_weekend,
                 re_completeness_area_score,
                 re_completeness_points_earned,
                 re_completeness_points_possible,
                 re_completeness_rate,
                 rn_days_compliant,
                 rn_rate,
                 score_cna,
                 score_lvn,
                 score_rn,
                 score_total_nursing,
                 score_total_weekend_nursing,
                 staffing_turnover_rate,
                 total_nursing_days_compliant,
                 total_nursing_rate,
                 total_weekend_days_compliant,
                 total_weekend_nursing_rate,
                 turnover_area_score,
                 turnover_points_earned,
                 turnover_possible_points)
             select 
                 achievement_points_antipsych,
                 achievement_points_fall,
                 achievement_points_pu,
                 acuity_area_score,
                 acuity_points_earned,
                 acuity_possible_points,
                 antipsych_denom_annotation,
                 antipsych_denom_pyr_annotation,
                 antipsych_denom_pyr,
                 antipsych_denom,
                 antipsych_metric_score,
                 antipsych_num_annotation,
                 antipsych_num_pyr_annotation,
                 antipsych_num_pyr,
                 antipsych_num,
                 antipsych_rate_annotation,
                 antipsych_rate_pyr_annotation,
                 antipsych_rate_pyr,
                 antipsych_rate,
                 ccn,
                 cna_days_compliant,
                 cna_rate,
                 facilityid,
                 facility_name,
                 fall_denom_annotation,
                 fall_denom_pyr_annotation,
                 fall_denom_pyr,
                 fall_denom,
                 fall_metric_score,
                 fall_num_annotation,
                 fall_num_pyr_annotation,
                 fall_num_pyr,
                 fall_num,
                 fall_rate_annotation,
                 fall_rate_pyr_annotation,
                 fall_rate_pyr,
                 fall_rate,
                 gap_closure_antipsych_annotation,
                 gap_closure_antipsych,
                 gap_closure_fall_annotation,
                 gap_closure_fall,
                 gap_closure_pu_annotation,
                 gap_closure_pu,
                 hcai_id,
                 improvement_points_antipsych,
                 improvement_points_fall,
                 improvement_points_pu,
                 lvn_days_compliant,
                 lvn_rate,
                 mds_area_score,
                 mds_data_completeness,
                 mds_points_earned,
                 mds_points_possible,
                 medi_cal_share_area_score,
                 medi_cal_share_footnote,
                 medi_cal_share_points_earned,
                 medi_cal_share_possible_points,
                 medi_cal_share_rate,
                 npi,
                 pu_denom_annotation,
                 pu_denom_pyr_annotation,
                 pu_denom_pyr,
                 pu_denom,
                 pu_metric_score,
                 pu_num_annotation,
                 pu_num_pyr_annotation,
                 pu_num_pyr,
                 pu_num,
                 pu_rate_annotation,
                 pu_rate_pyr_annotation,
                 pu_rate_pyr,
                 pu_rate,
                 raw_mds_score,
                 raw_score_cna,
                 raw_score_lvn,
                 raw_score_rn,
                 raw_score_total_nursing,
                 raw_score_weekend,
                 re_completeness_area_score,
                 re_completeness_points_earned,
                 re_completeness_points_possible,
                 re_completeness_rate,
                 rn_days_compliant,
                 rn_rate,
                 score_cna,
                 score_lvn,
                 score_rn,
                 score_total_nursing,
                 score_total_weekend_nursing,
                 staffing_turnover_rate,
                 total_nursing_days_compliant,
                 total_nursing_rate,
                 total_weekend_days_compliant,
                 total_weekend_nursing_rate,
                 turnover_area_score,
                 turnover_points_earned,
                 turnover_possible_points
             from wqip_quarterly_performance_2023_r1"""

    csv.db_exec_sql(sql)

    # ------------------

    sql = "update wqip_quarterly_performance set quarter = '2023-r1'"
    csv.db_exec_sql(sql)

    sql = """insert into wqip_quarterly_performance (
                 achievement_points_antipsych,
                 achievement_points_fall,
                 achievement_points_pu,
                 acuity_area_score,
                 acuity_points_earned,
                 acuity_possible_points,
                 antipsych_denom_annotation,
                 antipsych_denom_pyr_annotation,
                 antipsych_denom_pyr,
                 antipsych_denom,
                 antipsych_metric_score,
                 antipsych_num_annotation,
                 antipsych_num_pyr_annotation,
                 antipsych_num_pyr,
                 antipsych_num,
                 antipsych_rate_annotation,
                 antipsych_rate_pyr_annotation,
                 antipsych_rate_pyr,
                 antipsych_rate,
                 ccn,
                 cna_days_compliant,
                 cna_rate,
                 facilityid,
                 facility_name,
                 fall_denom_annotation,
                 fall_denom_pyr_annotation,
                 fall_denom_pyr,
                 fall_denom,
                 fall_metric_score,
                 fall_num_annotation,
                 fall_num_pyr_annotation,
                 fall_num_pyr,
                 fall_num,
                 fall_rate_annotation,
                 fall_rate_pyr_annotation,
                 fall_rate_pyr,
                 fall_rate,
                 gap_closure_antipsych_annotation,
                 gap_closure_antipsych,
                 gap_closure_fall_annotation,
                 gap_closure_fall,
                 gap_closure_pu_annotation,
                 gap_closure_pu,
                 hcai_id,
                 improvement_points_antipsych,
                 improvement_points_fall,
                 improvement_points_pu,
                 lvn_days_compliant,
                 lvn_rate,
                 mds_area_score,
                 mds_data_completeness,
                 mds_points_earned,
                 mds_points_possible,
                 medi_cal_share_area_score,
                 medi_cal_share_points_earned,
                 medi_cal_share_possible_points,
                 medi_cal_share_rate,
                 npi,
                 pu_denom_annotation,
                 pu_denom_pyr_annotation,
                 pu_denom_pyr,
                 pu_denom,
                 pu_metric_score,
                 pu_num_annotation,
                 pu_num_pyr_annotation,
                 pu_num_pyr,
                 pu_num,
                 pu_rate_annotation,
                 pu_rate_pyr_annotation,
                 pu_rate_pyr,
                 pu_rate,
                 raw_mds_score,
                 raw_score_cna,
                 raw_score_lvn,
                 raw_score_rn,
                 raw_score_total_nursing,
                 raw_score_weekend,
                 re_completeness_area_score,
                 re_completeness_points_earned,
                 re_completeness_points_possible,
                 re_completeness_rate,
                 rn_days_compliant,
                 rn_rate,
                 score_cna,
                 score_lvn,
                 score_rn,
                 score_total_nursing,
                 score_total_weekend_nursing,
                 staffing_turnover_rate,
                 total_nursing_days_compliant,
                 total_nursing_rate,
                 total_weekend_days_compliant,
                 total_weekend_nursing_rate,
                 turnover_area_score,
                 turnover_points_earned,
                 turnover_possible_points)
             select 
                 achievement_points_antipsych,
                 achievement_points_fall,
                 achievement_points_pu,
                 acuity_area_score,
                 acuity_points_earned,
                 acuity_possible_points,
                 antipsych_denom_annotation,
                 antipsych_denom_pyr_annotation,
                 antipsych_denom_pyr,
                 antipsych_denom,
                 antipsych_metric_score,
                 antipsych_num_annotation,
                 antipsych_num_pyr_annotation,
                 antipsych_num_pyr,
                 antipsych_num,
                 antipsych_rate_annotation,
                 antipsych_rate_pyr_annotation,
                 antipsych_rate_pyr,
                 antipsych_rate,
                 ccn,
                 cna_days_compliant,
                 cna_rate,
                 facilityid,
                 facility_name,
                 fall_denom_annotation,
                 fall_denom_pyr_annotation,
                 fall_denom_pyr,
                 fall_denom,
                 fall_metric_score,
                 fall_num_annotation,
                 fall_num_pyr_annotation,
                 fall_num_pyr,
                 fall_num,
                 fall_rate_annotation,
                 fall_rate_pyr_annotation,
                 fall_rate_pyr,
                 fall_rate,
                 gap_closure_antipsych_annotation,
                 gap_closure_antipsych,
                 gap_closure_fall_annotation,
                 gap_closure_fall,
                 gap_closure_pu_annotation,
                 gap_closure_pu,
                 hcai_id,
                 improvement_points_antipsych,
                 improvement_points_fall,
                 improvement_points_pu,
                 lvn_days_compliant,
                 lvn_rate,
                 mds_area_score,
                 mds_data_completeness,
                 mds_points_earned,
                 mds_points_possible,
                 medi_cal_share_area_score,
                 medi_cal_share_points_earned,
                 medi_cal_share_possible_points,
                 medi_cal_share_rate,
                 npi,
                 pu_denom_annotation,
                 pu_denom_pyr_annotation,
                 pu_denom_pyr,
                 pu_denom,
                 pu_metric_score,
                 pu_num_annotation,
                 pu_num_pyr_annotation,
                 pu_num_pyr,
                 pu_num,
                 pu_rate_annotation,
                 pu_rate_pyr_annotation,
                 pu_rate_pyr,
                 pu_rate,
                 raw_mds_score,
                 raw_score_cna,
                 raw_score_lvn,
                 raw_score_rn,
                 raw_score_total_nursing,
                 raw_score_weekend,
                 re_completeness_area_score,
                 re_completeness_points_earned,
                 re_completeness_points_possible,
                 re_completeness_rate,
                 rn_days_compliant,
                 rn_rate,
                 score_cna,
                 score_lvn,
                 score_rn,
                 score_total_nursing,
                 score_total_weekend_nursing,
                 staffing_turnover_rate,
                 total_nursing_days_compliant,
                 total_nursing_rate,
                 total_weekend_days_compliant,
                 total_weekend_nursing_rate,
                 turnover_area_score,
                 turnover_points_earned,
                 turnover_possible_points
             from wqip_quarterly_performance_2023_r2"""

    csv.db_exec_sql(sql)

    sql = "update wqip_quarterly_performance set quarter = '2023-r2' where quarter is NULL"
    csv.db_exec_sql(sql)

    # ------------------

    sql = """insert into wqip_quarterly_performance (
                 achievement_points_antipsych,
                 achievement_points_fall,
                 achievement_points_pu,
                 acuity_area_score,
                 acuity_points_earned,
                 acuity_possible_points,
                 antipsych_denom_annotation,
                 antipsych_denom_pyr_annotation,
                 antipsych_denom_pyr,
                 antipsych_denom,
                 antipsych_metric_score,
                 antipsych_num_annotation,
                 antipsych_num_pyr_annotation,
                 antipsych_num_pyr,
                 antipsych_num,
                 antipsych_rate_annotation,
                 antipsych_rate_pyr_annotation,
                 antipsych_rate_pyr,
                 antipsych_rate,
                 ccn,
                 cna_days_compliant,
                 cna_rate,
                 facilityid,
                 facility_name,
                 fall_denom_annotation,
                 fall_denom_pyr_annotation,
                 fall_denom_pyr,
                 fall_denom,
                 fall_metric_score,
                 fall_num_annotation,
                 fall_num_pyr_annotation,
                 fall_num_pyr,
                 fall_num,
                 fall_rate_annotation,
                 fall_rate_pyr_annotation,
                 fall_rate_pyr,
                 fall_rate,
                 gap_closure_antipsych_annotation,
                 gap_closure_antipsych,
                 gap_closure_fall_annotation,
                 gap_closure_fall,
                 gap_closure_pu_annotation,
                 gap_closure_pu,
                 hcai_id,
                 improvement_points_antipsych,
                 improvement_points_fall,
                 improvement_points_pu,
                 lvn_days_compliant,
                 lvn_rate,
                 mds_area_score,
                 mds_data_completeness,
                 mds_points_earned,
                 mds_points_possible,
                 medi_cal_share_area_score,
                 medi_cal_share_points_earned,
                 medi_cal_share_possible_points,
                 medi_cal_share_rate,
                 npi1,
                 npi2,
                 npi3,
                 pu_denom_annotation,
                 pu_denom_pyr_annotation,
                 pu_denom_pyr,
                 pu_denom,
                 pu_metric_score,
                 pu_num_annotation,
                 pu_num_pyr_annotation,
                 pu_num_pyr,
                 pu_num,
                 pu_rate_annotation,
                 pu_rate_pyr_annotation,
                 pu_rate_pyr,
                 pu_rate,
                 raw_mds_score,
                 raw_score_cna,
                 raw_score_lvn,
                 raw_score_rn,
                 raw_score_total_nursing,
                 raw_score_weekend,
                 re_completeness_area_score,
                 re_completeness_points_earned,
                 re_completeness_points_possible,
                 re_completeness_rate,
                 rn_days_compliant,
                 rn_rate,
                 score_cna,
                 score_lvn,
                 score_rn,
                 score_total_nursing,
                 score_total_weekend_nursing,
                 staffing_turnover_rate,
                 total_nursing_days_compliant,
                 total_nursing_rate,
                 total_weekend_days_compliant,
                 total_weekend_nursing_rate,
                 turnover_area_score,
                 turnover_points_earned,
                 turnover_possible_points)
             select
                 achievement_points_antipsych,
                 achievement_points_fall,
                 achievement_points_pu,
                 acuity_area_score,
                 acuity_points_earned,
                 acuity_possible_points,
                 antipsych_denom_annotation,
                 antipsych_denom_pyr_annotation,
                 antipsych_denom_pyr,
                 antipsych_denom,
                 antipsych_metric_score,
                 antipsych_num_annotation,
                 antipsych_num_pyr_annotation,
                 antipsych_num_pyr,
                 antipsych_num,
                 antipsych_rate_annotation,
                 antipsych_rate_pyr_annotation,
                 antipsych_rate_pyr,
                 antipsych_rate,
                 ccn,
                 cna_days_compliant,
                 cna_rate,
                 facilityid,
                 facility_name,
                 fall_denom_annotation,
                 fall_denom_pyr_annotation,
                 fall_denom_pyr,
                 fall_denom,
                 fall_metric_score,
                 fall_num_annotation,
                 fall_num_pyr_annotation,
                 fall_num_pyr,
                 fall_num,
                 fall_rate_annotation,
                 fall_rate_pyr_annotation,
                 fall_rate_pyr,
                 fall_rate,
                 gap_closure_antipsych_annotation,
                 gap_closure_antipsych,
                 gap_closure_fall_annotation,
                 gap_closure_fall,
                 gap_closure_pu_annotation,
                 gap_closure_pu,
                 hcai_id,
                 improvement_points_antipsych,
                 improvement_points_fall,
                 improvement_points_pu,
                 lvn_days_compliant,
                 lvn_rate,
                 mds_area_score,
                 mds_data_completeness,
                 mds_points_earned,
                 mds_points_possible,
                 medi_cal_share_area_score,
                 medi_cal_share_points_earned,
                 medi_cal_share_possible_points,
                 medi_cal_share_rate,
                 npi1,
                 npi2,
                 npi3,
                 pu_denom_annotation,
                 pu_denom_pyr_annotation,
                 pu_denom_pyr,
                 pu_denom,
                 pu_metric_score,
                 pu_num_annotation,
                 pu_num_pyr_annotation,
                 pu_num_pyr,
                 pu_num,
                 pu_rate_annotation,
                 pu_rate_pyr_annotation,
                 pu_rate_pyr,
                 pu_rate,
                 raw_mds_score,
                 raw_score_cna,
                 raw_score_lvn,
                 raw_score_rn,
                 raw_score_total_nursing,
                 raw_score_weekend,
                 re_completeness_area_score,
                 re_completeness_points_earned,
                 re_completeness_points_possible,
                 re_completeness_rate,
                 rn_days_compliant,
                 rn_rate,
                 score_cna,
                 score_lvn,
                 score_rn,
                 score_total_nursing,
                 score_total_weekend_nursing,
                 staffing_turnover_rate,
                 total_nursing_days_compliant,
                 total_nursing_rate,
                 total_weekend_days_compliant,
                 total_weekend_nursing_rate,
                 turnover_area_score,
                 turnover_points_earned,
                 turnover_possible_points
             from wqip_quarterly_performance_2023_r3"""

    csv.db_exec_sql(sql)
 
    sql = "update wqip_quarterly_performance set quarter = '2023-r3' where quarter is NULL"
    csv.db_exec_sql(sql)

    # ------------------

    sql = """insert into wqip_quarterly_performance (
                 antipsych_denom_annotation,
                 antipsych_denom,
                 antipsych_num_annotation,
                 antipsych_num,
                 antipsych_rate_annotation,
                 antipsych_rate,
                 ccn,
                 cna_days_compliant,
                 cna_rate,
                 facilityid,
                 facility_name,
                 fall_denom_annotation,
                 fall_denom,
                 fall_num_annotation,
                 fall_num,
                 fall_rate_annotation,
                 fall_rate,
                 hcai_id,
                 ltmw_denom_annotation,
                 ltmw_denom,
                 ltmw_num_annotation,
                 ltmw_num,
                 ltmw_rate_annotation,
                 ltmw_rate,
                 lvn_days_compliant,
                 lvn_rate,
                 medi_cal_share_rate,
                 npi1,
                 npi2,
                 npi3,
                 re_completeness_rate,
                 rn_days_compliant,
                 rn_rate,
                 staffing_turnover_rate,
                 total_nursing_days_compliant,
                 total_nursing_rate,
                 total_weekend_days_compliant,
                 total_weekend_nursing_rate)
             select
                 antipsych_denom_annotation,
                 antipsych_denom,
                 antipsych_num_annotation,
                 antipsych_num,
                 antipsych_rate_annotation,
                 antipsych_rate,
                 ccn,
                 cna_days_compliant,
                 cna_rate,
                 facilityid,
                 facility_name,
                 fall_denom_annotation,
                 fall_denom,
                 fall_num_annotation,
                 fall_num,
                 fall_rate_annotation,
                 fall_rate,
                 hcai_id,
                 ltmw_denom_annotation,
                 ltmw_denom,
                 ltmw_num_annotation,
                 ltmw_num,
                 ltmw_rate_annotation,
                 ltmw_rate,
                 lvn_days_compliant,
                 lvn_rate,
                 medi_cal_share_rate,
                 npi1,
                 npi2,
                 npi3,
                 re_completeness_rate,
                 rn_days_compliant,
                 rn_rate,
                 staffing_turnover_rate,
                 total_nursing_days_compliant,
                 total_nursing_rate,
                 total_weekend_days_compliant,
                 total_weekend_nursing_rate
             from wqip_quarterly_performance_2024_r1"""

    csv.db_exec_sql(sql)

    sql = "update wqip_quarterly_performance set quarter = '2024-r1' where quarter is NULL"
    csv.db_exec_sql(sql)

    csv.db_exec_sql("drop table if exists wqip_quarterly_performance_2023_r1")
    csv.db_exec_sql("drop table if exists wqip_quarterly_performance_2023_r2")
    csv.db_exec_sql("drop table if exists wqip_quarterly_performance_2023_r3")
    csv.db_exec_sql("drop table if exists wqip_quarterly_performance_2024_r1")

    print("")

